package gov.gsa.pivconformancetest;

import gov.gsa.pivconformance.card.client.*;
import gov.gsa.pivconformance.utils.OSUtils;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.TestReporter;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.fail;

public class X509DataObjectTests {
    @DisplayName("Test X.509 Data Object parsing")
    @ParameterizedTest(name = "{index} => oid = {0}, file = {1}")
    @MethodSource("dataObjectTestProvider")
    void dataObjectTest(String oid, String file, TestReporter reporter) {
        assertNotNull(oid);
        assertNotNull(file);
        Path filePath = Paths.get(OSUtils.getTempDir(), file);
        byte[] fileData = null;
        try {
            fileData = Files.readAllBytes(filePath);
        } catch (IOException e) {
            fail(e);
        }
        PIVDataObject o = PIVDataObjectFactory.createDataObjectForOid(oid);
        assertNotNull(o);
        reporter.publishEntry(oid, o.getClass().getSimpleName());

        //XXX Unit tests will need to be updated files here are just cert files not card data objects.

        o.setOID(oid);
        o.setBytes(fileData);
        assert(o.decode());
    }

    private static Stream<Arguments> dataObjectTestProvider() {
        return Stream.of(
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/01_Golden_PIV/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/02_Golden_PIV-I/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/03_SKID_Mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/04_Tampered_CHUID/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/05_Tampered_Certificates/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/06_Tampered_PHOTO/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/07_Tampered_Fingerprints/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/08_Tampered_Security_Object/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/09_Expired_CHUID_Signer/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/10_Expired_Cert_Signer/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/11_Certs_Expire_after_CHUID/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/12_Certs_not_yet_valid/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/13_Certs_are_expired/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/14_Expired_CHUID/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/15_CHUID_FASCN_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/16_Card_Auth_FASCN_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/17_PHOTO_FASCN_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/18_Fingerprints_FASCN_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/19_CHUID_UUID_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/20_Card_Auth_UUID_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/21_PHOTO_UUID_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/22_Fingerprints_UUID_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/23_Public_Private_Key_mismatch/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/24_Revoked_Certificates/3 - PIV_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/25_Disco_Object_Not_Present/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/25_Disco_Object_Not_Present/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_Missing_DO.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/26_Disco_Object_Present_App_PIN_Only/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/26_Disco_Object_Present_App_PIN_Only/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_App_PIN_Only.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/27_Disco_Object_Present_App_PIN_Primary/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/27_Disco_Object_Present_App_PIN_Primary/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_App_PIN_Prim.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/28_Disco_Object_Present_Global_PIN_Primary/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/28_Disco_Object_Present_Global_PIN_Primary/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_Global_PIN_Prim.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/37_Golden_FIPS_201-2_PIV_PPS_F=512_D=64/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/37_Golden_FIPS_201-2_PIV_PPS_F=512_D=64/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_PPS.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/38_Bad_Hash_in_Sec_Object/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/38_Bad_Hash_in_Sec_Object/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_Bad_SO_Hash.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/39_Golden_FIPS_201-2_Fed_PIV-I/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/39_Golden_FIPS_201-2_Fed_PIV-I/3 - ICAM_Test_Card_PIV-I_Auth_Fed_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/41_Re-keyed_Card/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/41_Re-keyed_Card/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_Re-key.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/42_OCSP_Expired/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/42_OCSP_Expired/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_OCSP_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/43_OCSP_revoked_w_nocheck/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/43_OCSP_revoked_w_nocheck/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_OCSP_Revoked_NOCHECK.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/44_OCSP_revoked_wo_nocheck/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/44_OCSP_revoked_wo_nocheck/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_OCSP_Revoked_WO_NOCHECK.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/45_OCSP_Invalid_Signature/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/45_OCSP_Invalid_Signature/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_OCSP_Invalid_Signature.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/46_Golden_FIPS_201-2_PIV/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/46_Golden_FIPS_201-2_PIV/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/47_Golden_FIPS_201-2_PIV_SAN_Order/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/47_Golden_FIPS_201-2_PIV_SAN_Order/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_SAN_Order.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/48_T=0_with_Non-Zero_PPS_LEN_Value/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/48_T=0_with_Non-Zero_PPS_LEN_Value/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_Non-Zero_PPS_LEN.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/49_FIPS_201-2_Facial_Image_CBEFF_Expired/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/49_FIPS_201-2_Facial_Image_CBEFF_Expired/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_FI_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/50_FIPS_201-2_Facial_Image_CBEFF_Expires_before_CHUID/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/50_FIPS_201-2_Facial_Image_CBEFF_Expires_before_CHUID/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_FI_will_Expire.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/51_FIPS_201-2_Fingerprint_CBEFF_Expired/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/51_FIPS_201-2_Fingerprint_CBEFF_Expired/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_FP_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/52_FIPS_201-2_Fingerprint_CBEFF_Expires_before_CHUID/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/52_FIPS_201-2_Fingerprint_CBEFF_Expires_before_CHUID/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_FP_will_Expire.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/53_FIPS_201-2_Large_Card_Auth_Cert/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/53_FIPS_201-2_Large_Card_Auth_Cert/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_Large_Cert.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/54_Golden_FIPS_201-2_NFI_PIV-I/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/54_Golden_FIPS_201-2_NFI_PIV-I/3 - ICAM_Test_Card_PIV-I_Auth_NFI_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/55_FIPS_201-2_Missing_Security_Object/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/55_FIPS_201-2_Missing_Security_Object/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_Missing_SO.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/56_FIPS_201-2_Signer_Expires/3 - ICAM_PIV_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_PIV_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/56_FIPS_201-2_Signer_Expires/3 - ICAM_Test_Card_PIV_Auth_SP_800-73-4_Signer_Expires.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/01_Golden_PIV/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/02_Golden_PIV-I/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/03_SKID_Mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/04_Tampered_CHUID/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/05_Tampered_Certificates/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/06_Tampered_PHOTO/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/07_Tampered_Fingerprints/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/08_Tampered_Security_Object/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/09_Expired_CHUID_Signer/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/10_Expired_Cert_Signer/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/11_Certs_Expire_after_CHUID/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/12_Certs_not_yet_valid/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/13_Certs_are_expired/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/14_Expired_CHUID/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/15_CHUID_FASCN_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/16_Card_Auth_FASCN_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/17_PHOTO_FASCN_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/18_Fingerprints_FASCN_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/19_CHUID_UUID_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/20_Card_Auth_UUID_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/21_PHOTO_UUID_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/22_Fingerprints_UUID_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/23_Public_Private_Key_mismatch/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/24_Revoked_Certificates/4 - PIV_Card_Auth.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/25_Disco_Object_Not_Present/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/25_Disco_Object_Not_Present/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_Missing_DO.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/26_Disco_Object_Present_App_PIN_Only/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/26_Disco_Object_Present_App_PIN_Only/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_App_PIN_Only.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/27_Disco_Object_Present_App_PIN_Primary/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/27_Disco_Object_Present_App_PIN_Primary/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_App_PIN_Prim.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/28_Disco_Object_Present_Global_PIN_Primary/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/28_Disco_Object_Present_Global_PIN_Primary/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_Global_PIN_Prim.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/37_Golden_FIPS_201-2_PIV_PPS_F=512_D=64/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/37_Golden_FIPS_201-2_PIV_PPS_F=512_D=64/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_PPS.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/38_Bad_Hash_in_Sec_Object/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/38_Bad_Hash_in_Sec_Object/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_Bad_SO_Hash.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/39_Golden_FIPS_201-2_Fed_PIV-I/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/39_Golden_FIPS_201-2_Fed_PIV-I/4 - ICAM_Test_Card_PIV-I_Dig_Sig_Fed_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/41_Re-keyed_Card/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/41_Re-keyed_Card/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_Re-key.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/42_OCSP_Expired/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/42_OCSP_Expired/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_OCSP_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/43_OCSP_revoked_w_nocheck/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/43_OCSP_revoked_w_nocheck/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_OCSP_Revoked_NOCHECK.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/44_OCSP_revoked_wo_nocheck/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/44_OCSP_revoked_wo_nocheck/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_OCSP_Revoked_WO_NOCHECK.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/45_OCSP_Invalid_Signature/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/45_OCSP_Invalid_Signature/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_OCSP_Invalid_Signature.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/46_Golden_FIPS_201-2_PIV/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/46_Golden_FIPS_201-2_PIV/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/47_Golden_FIPS_201-2_PIV_SAN_Order/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/47_Golden_FIPS_201-2_PIV_SAN_Order/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_SAN_Order.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/48_T=0_with_Non-Zero_PPS_LEN_Value/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/48_T=0_with_Non-Zero_PPS_LEN_Value/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_Non-Zero_PPS_LEN.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/49_FIPS_201-2_Facial_Image_CBEFF_Expired/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/49_FIPS_201-2_Facial_Image_CBEFF_Expired/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_FI_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/50_FIPS_201-2_Facial_Image_CBEFF_Expires_before_CHUID/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/50_FIPS_201-2_Facial_Image_CBEFF_Expires_before_CHUID/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_FI_will_Expire.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/51_FIPS_201-2_Fingerprint_CBEFF_Expired/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/51_FIPS_201-2_Fingerprint_CBEFF_Expired/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_FP_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/52_FIPS_201-2_Fingerprint_CBEFF_Expires_before_CHUID/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/52_FIPS_201-2_Fingerprint_CBEFF_Expires_before_CHUID/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_FP_will_Expire.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/53_FIPS_201-2_Large_Card_Auth_Cert/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/53_FIPS_201-2_Large_Card_Auth_Cert/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_Large_Cert.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/54_Golden_FIPS_201-2_NFI_PIV-I/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/54_Golden_FIPS_201-2_NFI_PIV-I/4 - ICAM_Test_Card_PIV-I_Dig_Sig_NFI_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/55_FIPS_201-2_Missing_Security_Object/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/55_FIPS_201-2_Missing_Security_Object/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_Missing_SO.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/56_FIPS_201-2_Signer_Expires/4 - ICAM_PIV_Dig_Sig_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_DIGITAL_SIGNATURE_OID,
                        "cards/ICAM_Card_Objects/56_FIPS_201-2_Signer_Expires/4 - ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_Signer_Expires.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/25_Disco_Object_Not_Present/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/25_Disco_Object_Not_Present/5 - ICAM_Test_Card_PIV_Key_Mgmt_Auth_SP_800-73-4_Missing_DO.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/26_Disco_Object_Present_App_PIN_Only/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/26_Disco_Object_Present_App_PIN_Only/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_App_PIN_Only.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/27_Disco_Object_Present_App_PIN_Primary/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/27_Disco_Object_Present_App_PIN_Primary/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_App_PIN_Prim.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/28_Disco_Object_Present_Global_PIN_Primary/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/28_Disco_Object_Present_Global_PIN_Primary/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_Global_PIN_Prim.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/37_Golden_FIPS_201-2_PIV_PPS_F=512_D=64/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/37_Golden_FIPS_201-2_PIV_PPS_F=512_D=64/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_PPS.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/38_Bad_Hash_in_Sec_Object/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/38_Bad_Hash_in_Sec_Object/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_Bad_SO_Hash.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/39_Golden_FIPS_201-2_Fed_PIV-I/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/39_Golden_FIPS_201-2_Fed_PIV-I/5 - ICAM_Test_Card_PIV-I_Key_Mgmt_Fed_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/41_Re-keyed_Card/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/41_Re-keyed_Card/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_Re-key.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/42_OCSP_Expired/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/42_OCSP_Expired/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_OCSP_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/43_OCSP_revoked_w_nocheck/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/43_OCSP_revoked_w_nocheck/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_OCSP_Revoked_NOCHECK.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/44_OCSP_revoked_wo_nocheck/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/44_OCSP_revoked_wo_nocheck/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_OCSP_Revoked_WO_NOCHECK.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/45_OCSP_Invalid_Signature/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/45_OCSP_Invalid_Signature/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_OCSP_Invalid_Signature.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/46_Golden_FIPS_201-2_PIV/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/46_Golden_FIPS_201-2_PIV/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/47_Golden_FIPS_201-2_PIV_SAN_Order/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/47_Golden_FIPS_201-2_PIV_SAN_Order/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_SAN_Order.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/48_T=0_with_Non-Zero_PPS_LEN_Value/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/48_T=0_with_Non-Zero_PPS_LEN_Value/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_Non-Zero_PPS_LEN.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/49_FIPS_201-2_Facial_Image_CBEFF_Expired/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/49_FIPS_201-2_Facial_Image_CBEFF_Expired/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_FI_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/50_FIPS_201-2_Facial_Image_CBEFF_Expires_before_CHUID/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/50_FIPS_201-2_Facial_Image_CBEFF_Expires_before_CHUID/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_FI_will_Expire.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/51_FIPS_201-2_Fingerprint_CBEFF_Expired/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/51_FIPS_201-2_Fingerprint_CBEFF_Expired/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_FP_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/52_FIPS_201-2_Fingerprint_CBEFF_Expires_before_CHUID/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/52_FIPS_201-2_Fingerprint_CBEFF_Expires_before_CHUID/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_FP_will_Expire.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/53_FIPS_201-2_Large_Card_Auth_Cert/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/53_FIPS_201-2_Large_Card_Auth_Cert/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_Large_Cert.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/54_Golden_FIPS_201-2_NFI_PIV-I/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/54_Golden_FIPS_201-2_NFI_PIV-I/5 - ICAM_Test_Card_PIV-I_Key_Mgmt_NFI_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/55_FIPS_201-2_Missing_Security_Object/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/55_FIPS_201-2_Missing_Security_Object/5 - ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_Missing_SO.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/56_FIPS_201-2_Signer_Expires/5 - ICAM_PIV_Key_Mgmt_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_KEY_MANAGEMENT_OID,
                        "cards/ICAM_Card_Objects/56_FIPS_201-2_Signer_Expires/5 - ICAM_Test_Card_PIV_Key_Mgmt_Auth_SP_800-73-4_Signer_Expires.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/25_Disco_Object_Not_Present/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/25_Disco_Object_Not_Present/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_Missing_DO.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/26_Disco_Object_Present_App_PIN_Only/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/26_Disco_Object_Present_App_PIN_Only/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_App_PIN_Only.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/27_Disco_Object_Present_App_PIN_Primary/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/27_Disco_Object_Present_App_PIN_Primary/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_App_PIN_Prim.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/28_Disco_Object_Present_Global_PIN_Primary/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/28_Disco_Object_Present_Global_PIN_Primary/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_Global_PIN_Prim.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/37_Golden_FIPS_201-2_PIV_PPS_F=512_D=64/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/37_Golden_FIPS_201-2_PIV_PPS_F=512_D=64/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_PPS.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/38_Bad_Hash_in_Sec_Object/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/38_Bad_Hash_in_Sec_Object/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_Bad_SO_Hash.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/39_Golden_FIPS_201-2_Fed_PIV-I/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/39_Golden_FIPS_201-2_Fed_PIV-I/6 - ICAM_Test_Card_PIV-I_Card_Auth_Fed_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/41_Re-keyed_Card/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/41_Re-keyed_Card/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_Re-key.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/42_OCSP_Expired/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/42_OCSP_Expired/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_OCSP_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/43_OCSP_revoked_w_nocheck/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/43_OCSP_revoked_w_nocheck/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_OCSP_Revoked_NOCHECK.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/44_OCSP_revoked_wo_nocheck/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/44_OCSP_revoked_wo_nocheck/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_OCSP_Revoked_WO_NOCHECK.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/45_OCSP_Invalid_Signature/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/45_OCSP_Invalid_Signature/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_OCSP_Invalid_Signature.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/46_Golden_FIPS_201-2_PIV/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/46_Golden_FIPS_201-2_PIV/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/47_Golden_FIPS_201-2_PIV_SAN_Order/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/47_Golden_FIPS_201-2_PIV_SAN_Order/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_SAN_Order.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/48_T=0_with_Non-Zero_PPS_LEN_Value/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/48_T=0_with_Non-Zero_PPS_LEN_Value/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_Non-Zero_PPS_LEN.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/49_FIPS_201-2_Facial_Image_CBEFF_Expired/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/49_FIPS_201-2_Facial_Image_CBEFF_Expired/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_FI_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/50_FIPS_201-2_Facial_Image_CBEFF_Expires_before_CHUID/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/50_FIPS_201-2_Facial_Image_CBEFF_Expires_before_CHUID/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_FI_will_Expire.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/51_FIPS_201-2_Fingerprint_CBEFF_Expired/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/51_FIPS_201-2_Fingerprint_CBEFF_Expired/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_FP_Expired.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/52_FIPS_201-2_Fingerprint_CBEFF_Expires_before_CHUID/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/52_FIPS_201-2_Fingerprint_CBEFF_Expires_before_CHUID/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_FP_will_Expire.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/53_FIPS_201-2_Large_Card_Auth_Cert/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/53_FIPS_201-2_Large_Card_Auth_Cert/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_Large_Cert.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/54_Golden_FIPS_201-2_NFI_PIV-I/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/54_Golden_FIPS_201-2_NFI_PIV-I/6 - ICAM_Test_Card_PIV-I_Card_Auth_NFI_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/55_FIPS_201-2_Missing_Security_Object/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/55_FIPS_201-2_Missing_Security_Object/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_Missing_SO.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/56_FIPS_201-2_Signer_Expires/6 - ICAM_PIV_Card_Auth_SP_800-73-4.crt"),
                Arguments.of(APDUConstants.X509_CERTIFICATE_FOR_CARD_AUTHENTICATION_OID,
                        "cards/ICAM_Card_Objects/56_FIPS_201-2_Signer_Expires/6 - ICAM_Test_Card_PIV_Card_Auth_SP_800-73-4_Signer_Expires.crt")
                );
    }
}
